# Site settings
title: Cora in Chicago
description: 'An enthusiastic coder'
# url: 'http://joshgerdes.com/jekyll-uno'
url: '/corainchicago.github.io'
baseurl: 
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Cora Fedesna'
  email: cfedesna@gmail.com
  twitter_username: corainchicago
  facebook_username: 
  github_username:  corainchicago
  linkedin_username:  corainchicago

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: blog/:title/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

gems:
  - jekyll-paginate

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
